const routes = [
  {
    name: 'Home',
    route: 'Home',
    icon: 'home',
    typeIcon: 'MaterialIcons',
    bg: '#477EEA',
  },
  {
    name: 'Anatomy',
    route: 'Anatomy',
    icon: 'phone-portrait-outline',
    typeIcon: 'Ionicons',
    bg: '#C5F442',
  },
  {
    name: 'Header',
    route: 'Header',
    icon: 'arrow-up',
    typeIcon: 'Ionicons',
    bg: '#477EEA',
    types: '12',
  },
  {
    name: 'Footer',
    route: 'Footer',
    icon: 'arrow-down',
    typeIcon: 'Ionicons',
    bg: '#DA4437',
    types: '4',
  },
  {
    name: 'Accordion',
    route: 'Accordion',
    icon: 'repeat',
    typeIcon: 'MaterialIcons',
    bg: '#C5F442',
    types: '5',
  },
  {
    name: 'ActionSheet',
    route: 'ActionSheet',
    icon: 'easel',
    typeIcon: 'Ionicons',
    bg: '#C5F442',
    types: '2',
  },
  {
    name: 'Badge',
    route: 'Badge',
    icon: 'notifications',
    typeIcon: 'MaterialIcons',
    bg: '#4DCAE0',
  },
  {
    name: 'Button',
    route: 'Buttons',
    icon: 'radio-button-off',
    typeIcon: 'Ionicons',
    bg: '#1EBC7C',
    types: '9',
  },
  {
    name: 'Card',
    route: 'Card',
    icon: 'keypad',
    typeIcon: 'Ionicons',
    bg: '#B89EF5',
    types: '8',
  },
  {
    name: 'Check Box',
    route: 'Checkbox',
    icon: 'checkmark-circle',
    typeIcon: 'Ionicons',
    bg: '#EB6B23',
  },
  {
    name: 'Date Picker',
    route: 'DatePicker',
    icon: 'calendar',
    typeIcon: 'Ionicons',
    bg: '#EB6B23',
  },
  {
    name: 'Deck Swiper',
    route: 'DeckSwiper',
    icon: 'swap',
    typeIcon: 'Entypo',
    bg: '#3591FA',
    types: '2',
  },
  {
    name: 'Fab',
    route: 'Fabs',
    icon: 'help-buoy',
    bg: '#EF6092',
    types: '2',
  },
  {
    name: 'Form & Inputs',
    route: 'Form',
    icon: 'call',
    typeIcon: 'Ionicons',
    bg: '#EFB406',
    types: '14',
  },
  {
    name: 'Icon',
    route: 'Icon',
    icon: 'information-circle',
    typeIcon: 'Ionicons',
    bg: '#bfe9ea',
    types: '13',
  },
  {
    name: 'Layout',
    route: 'Layout',
    icon: 'grid',
    typeIcon: 'Ionicons',
    bg: '#9F897C',
  },
  {
    name: 'List',
    route: 'List',
    icon: 'lock',
    typeIcon: 'Entypo',
    bg: '#5DCEE2',
    types: '9',
  },
  {
    name: 'Picker',
    route: 'Picker',
    icon: 'arrow-down',
    typeIcon: 'Entypo',
    bg: '#F50C75',
    types: '9',
  },
  {
    name: 'Radio',
    route: 'Radio',
    icon: 'radio-button-on',
    typeIcon: 'Ionicons',
    bg: '#6FEA90',
    types: '2',
  },
  {
    name: 'SearchBar',
    route: 'SearchBar',
    icon: 'search',
    typeIcon: 'Ionicons',
    bg: '#29783B',
  },
  {
    name: 'Segment',
    route: 'Segment',
    icon: 'menu',
    typeIcon: 'MaterialIcons',
    bg: '#0A2C6B',
    types: '3',
  },
  {
    name: 'Spinner',
    route: 'Spinner',
    icon: 'navigate',
    typeIcon: 'Ionicons',
    bg: '#BE6F50',
  },
  {
    name: 'Tabs',
    route: 'Tabs',
    icon: 'progress-full',
    typeIcon: 'Entypo',
    bg: '#AB6AED',
    types: '3',
  },
  {
    name: 'Thumbnail',
    route: 'Thumbnail',
    icon: 'image',
    typeIcon: 'Entypo',
    bg: '#cc0000',
  },
  {
    name: 'Toast',
    route: 'Toast',
    icon: 'albums',
    typeIcon: 'Ionicons',
    bg: '#C5F442',
    types: '6',
  },
  {
    name: 'Typography',
    route: 'Typography',
    icon: 'copy-sharp',
    typeIcon: 'Ionicons',
    bg: '#48525D',
  },
  {
    name: 'Components',
    route: 'Components',
    icon: 'puzzle',
    typeIcon: 'MaterialCommunityIcons',
    bg: '#3591FA',
    types: '6',
  },
  {
    name: 'Chat',
    route: 'Chat',
    icon: 'question-answer',
    typeIcon: 'MaterialIcons',
    bg: '#C5F442',
  },
];

export default routes;
